name: nubankt02
description: "Atividade: Implementação do protótipo App do Nubank"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/logonubank.png
    - assets/icons/iconevisualizacao.png
    - assets/icons/iconeajuda.png
    - assets/icons/Iconeconvite.png
    - assets/icons/icone.png
    - assets/icons/Ellipse.png
    - assets/icons/iconepagar.png
    - assets/icons/iconeemprestado.png
    - assets/icons/iconetransferir.png
    - assets/icons/iconedepositar.png
    - assets/icons/iconecartao.png
    - assets/images/picture1.jpg
    - assets/images/picture2.jpg
    - assets/images/picture3.jpg
    - assets/images/picture4.jpg
    - assets/icons/nubank-icon.png
